apiVersion: apps/v1
kind: Deployment
metadata:
  name: squid-deployment
  namespace: default
  labels:
    name: squid
spec:
  replicas: 1
  selector:
    matchLabels:
      app: squid
  template:
    metadata:
      labels:
        app: squid
    spec:
      containers:
        - name: squid
          image: docker.io/cyrriv/squid:3.5.20
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: conf
              mountPath: /etc/squid/squid.conf
              subPath: squid.conf
            - name: blacklist-ads
              mountPath: /etc/squid/blacklist_ads.txt
              subPath: blacklist_ads.txt
            - name: blacklist-sites
              mountPath: /etc/squid/blacklist_sites.txt
              subPath: blacklist_sites.txt
            - name: whitelist-kids
              mountPath: /etc/squid/whitelist_kids.txt
              subPath: whitelist_kids.txt
            - name: logs-data
              mountPath: /var/log/squid
              mountPath: /var/spool/squid
          ports:
            - containerPort: 3128
              protocol: TCP
      volumes:
        - name: conf
          confifMap:
            name: squid-conf
        - name: blacklist-ads
          confifMap:
            name: squid-blacklist-ads
        - name: blacklist-sites
          confifMap:
            name: squid-blacklist-sites
        - name: whitelist-kids
          confifMap:
            name: squid-whitelist-kids
        - name: logs
          persistentVolumeClaim:
            claimName: local-path-pvc
        - name: logs-data
          persistentVolumeClaim:
            claimName: local-path-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: squid-service
  labels:
    name: squid
spec:
  type: NodePort
  externalTrafficPolicy: Local
  ports:
    - port: 3128
      targetPort: 3128
      protocol: TCP
  selector:
    app: squid