apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-cyri-pi4
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: nginx-proxy.cyri.intra
    http:
      paths:
      - backend:
          serviceName: nginx-proxy-svc
          servicePort: 80
        path: /
        pathType: Prefix
  - host: squid.cyri.intra
    http:
      paths:
      - backend:
          serviceName: squid-service
          servicePort: 3128
        path: /
        pathType: Prefix
  - host: kibana.cyri.intra
    http:
      paths:
      - backend:
          serviceName: elk-svc-kibana-oss
          servicePort: 5601
        path: /
        pathType: Prefix