apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana-conf
  namespace: elk
  labels:
    app: kibana
data:
  kibana.yml: |
    # Default Kibana configuration for docker target
    server.name: "kibana"
    server.host: "0.0.0.0"
    elasticsearch.hosts: [ "http://elasticsearch-svc.elk.svc.cluster.local:9200" ]
    monitoring.ui.container.elasticsearch.enabled: true