apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-conf
  namespace: elk
  labels:
    app: elasticsearch
data:
  elasticsearch.yml: |
    cluster.name: "docker-cluster"
    network.host: 0.0.0.0
    discovery.type: single-node
    xpack.security.enabled: false
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-jvm
  namespace: elk
  labels:
    app: elasticsearch
data:
  jvm.options: |
    -Xms512m
    -Xmx1g


