apiVersion: v1
data:
  Corefile: |
    .:53 {
         rewrite stop {
          name regex (.*)\.cyri\.intra {1}.default.svc.cluster.local
          answer name (.*)\.default\.svc\.cluster\.local {1}.cyri.intra
          }
        errors
        health
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
          pods insecure
          fallthrough in-addr.arpa ip6.arpa
        }
        hosts /etc/coredns/NodeHosts {
          ttl 60
          reload 15s
          fallthrough
        }
        prometheus :9153
        forward . 192.168.0.29
        cache 30
        loop
        reload
        loadbalance
    }
  NodeHosts: |
    192.168.0.35 cyri-pi4
kind: ConfigMap
metadata:
  name: coredns
  namespace: kube-system