apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana-deployment
  namespace: default
  labels:
    name: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
        - name: kibana
          image: docker.elastic.co/kibana/kibana:7.17.1-arm64
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: kibana-conf
              mountPath: /usr/share/kibana/config/kibana.yml
              subPath: kibana.yml
          ports:
            - containerPort: 5601
              protocol: TCP
      volumes:
        - name: kibana-conf
          configMap:
            name: kibana-conf
---
apiVersion: v1
kind: Service
metadata:
  name: kibana-svc
  labels:
    name: kibana
spec:
  selector:
    app: kibana
  ports:
    - port: 5601
      targetPort: 5601
      protocol: TCP
      name: kibana
  type: NodePort
